### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by dilip00001** [Elliott-Chong/quizmify#1]
While trying to accessing the questions from openapi , It shows 500 internal server error. Is something wrong with "Strict_Output" file . I can't solve the error:500

**Comment by rohansaini8192** [comment]
Yes, I have the same issue as mentioned by @dilip00001

**Comment by AritraChatterjee22** [comment]
I am  facing the same issue too. If you guys have found any solution to it then please share.

**Comment by bhaveek424** [comment]
Facing the same error. @Elliott-Chong do you know what's wrong here? I've tried testing in Postman too.

**Comment by svssdeva** [comment]
Yes facing same error !!!!

**Comment by bhaveek424** [comment]
Guys I got it why we are getting the error. Its because we have to buy OpenAi api credits. I just bought $5 worth api credits and it's working. @dilip00001 @AritraChatterjee22 @rohansaini8192

**Comment by dilip00001** [comment]
Thank You @bhaveek424 now its working

**Comment by bhaveek424** [comment]
@dilip00001 you can close the issue now. Thank you.

**Comment by Elliott-Chong** [comment]
Thank you @bhaveek424 for the help!
